import { useEffect, useState } from "react";
import { fallbackDemoSteps } from "./demoData";

export default function StandaloneDemo() {
  const [step, setStep] = useState(0);
  const [playing, setPlaying] = useState(false);
  const active = fallbackDemoSteps[step];

  useEffect(() => {
    if (!playing) return;
    const timer = window.setInterval(() => {
      setStep((current) => {
        if (current >= fallbackDemoSteps.length - 1) {
          setPlaying(false);
          return current;
        }
        return current + 1;
      });
    }, 2400);
    return () => window.clearInterval(timer);
  }, [playing]);

  return (
    <main className="page page--wide demo-page">
      <section className="demo-hero card">
        <div>
          <p className="eyebrow">CausalAtlas / standalone replay</p>
          <h1>From evidence to experiment</h1>
          <p className="muted">A zero-backend, zero-API recorded walkthrough of an auditable biomedical reasoning pipeline.</p>
        </div>
        <span className="demo-badge">OFFLINE · READ ONLY</span>
      </section>
      <section className="demo-summary">
        <div><span>Pipeline</span><strong>13 stages</strong></div>
        <div><span>Mode</span><strong>Recorded</strong></div>
        <div><span>Network</span><strong>None</strong></div>
        <div><span>Data</span><strong>Curated replay</strong></div>
      </section>
      <section className="card demo-replay-card">
        <div className="section-heading">
          <div><p className="eyebrow">Guided replay</p><h2>{active.number} · {active.title}</h2></div>
          <button className="button button--primary" onClick={() => setPlaying((value) => !value)}>{playing ? "Pause replay" : "Play replay"}</button>
        </div>
        <p className="demo-replay-card__description">{active.description}</p>
        <div className="demo-result-grid">{active.metrics.map((metric) => <div key={metric}><span>Stage output</span><strong>{metric}</strong></div>)}</div>
        <p className="demo-artifact"><b>Illustrative artifact:</b> <code>{active.artifact}</code></p>
        <input aria-label="Replay position" type="range" min="0" max={fallbackDemoSteps.length - 1} value={step} onChange={(event) => { setStep(Number(event.target.value)); setPlaying(false); }} />
        <div className="demo-timeline">{fallbackDemoSteps.map((item, index) => <button key={item.number} className={index === step ? "is-active" : index < step ? "is-passed" : ""} onClick={() => { setStep(index); setPlaying(false); }}><span>{item.number}</span><small>{item.title}</small><em>{item.metrics[0]}</em></button>)}</div>
      </section>
      <footer className="card demo-cta"><div><h2>Explore the source</h2><p className="muted">This page is generated by the frontend build and works from a local file server or GitHub Pages.</p></div><a className="button" href="https://github.com/">GitHub repository ↗</a></footer>
    </main>
  );
}
